//初始化
export const AUTH_INIT_REQUEST = 'AUTH_INIT_REQUEST';
export const AUTH_INIT_SUCCESS = 'AUTH_INIT_SUCCESS';
export const AUTH_INIT_FAILURE = 'AUTH_INIT_FAILURE';
//退出，直接清除localstorage
export const AUTH_LOGOUT = 'AUTH_LOGOUT';
//登录
export const AUTH_LOGIN_REQUEST = 'AUTH_LOGIN_REQUEST';
export const AUTH_LOGIN_SUCCESS = 'AUTH_LOGIN_SUCCESS';
export const AUTH_LOGIN_FAILURE = 'AUTH_LOGIN_FAILURE';
//注册
export const AUTH_REGISTER_REQUEST = 'AUTH_REGISTER_REQUEST';
export const AUTH_REGISTER_SUCCESS = 'AUTH_REGISTER_SUCCESS';
export const AUTH_REGISTER_FAILURE = 'AUTH_REGISTER_FAILURE';
//个人信息设置
export const AUTH_SETTING_REQUEST = 'AUTH_SETTING_REQUEST';
export const AUTH_SETTING_SUCCESS = 'AUTH_SETTING_SUCCESS';
export const AUTH_SETTING_FAILURE = 'AUTH_SETTING_FAILURE';