//获取所有项目列表
export const GET_PROJECTS_REQUEST = 'GET_PROJECTS_REQUEST';
export const GET_PROJECTS_SUCCESS = 'GET_PROJECTS_SUCCESS';
export const GET_PROJECTS_FAILURE = 'GET_PROJECTS_FAILURE';
//获取单个项目
export const GET_PROJECT_REQUEST = 'GET_PROJECT_REQUEST';
export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';
export const GET_PROJECT_FAILURE = 'GET_PROJECT_FAILURE';
//发布项目
export const PUBLISH_PROJECT_REQUEST = 'PUBLISH_PROJECT_REQUEST';
export const PUBLISH_PROJECT_SUCCESS = 'PUBLISH_PROJECT_SUCCESS';
export const PUBLISH_PROJECT_FAILURE = 'PUBLISH_PROJECT_FAILURE';
//获取已发布项目
export const GET_PUBLISHED_REQUEST = 'GET_PUBLISHED_REQUEST';
export const GET_PUBLISHED_SUCCESS = 'GET_PUBLISHED_SUCCESS';
export const GET_PUBLISHED_FAILURE = 'GET_PUBLISHED_FAILURE';
//申请项目
export const APPLY_PROJECT_REQUEST = 'APPLY_PROJECT_REQUEST';
export const APPLY_PROJECT_SUCCESS = 'APPLY_PROJECT_SUCCESS';
export const APPLY_PROJECT_FAILURE = 'APPLY_PROJECT_FAILURE';
//获取已申请项目
export const GET_APPLIED_PROJECT_REQUEST = 'GET_APPLIED_PROJECT_REQUEST';
export const GET_APPLIED_PROJECT_SUCCESS = 'GET_APPLIED_PROJECT_SUCCESS';
export const GET_APPLIED_PROJECT_FAILURE = 'GET_APPLIED_PROJECT_FAILURE';
//获取已申请人列表
export const GET_APPLIER_LIST_REQUEST = 'GET_APPLIER_LIST_REQUEST';
export const GET_APPLIER_LIST_SUCCESS = 'GET_APPLIER_LIST_SUCCESS';
export const GET_APPLIER_LIST_FAILURE = 'GET_APPLIER_LIST_FAILURE';
//更改项目状态
export const UPDATE_PROJECT_REQUEST = 'UPDATE_PROJECT_REQUEST';
export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';
export const UPDATE_PROJECT_FAILURE = 'UPDATE_PROJECT_FAILURE';
//更改申请状态
export const UPDATE_APPLIER_LIST_REQUEST = 'UPDATE_APPLIER_LIST_REQUEST';
export const UPDATE_APPLIER_LIST_SUCCESS = 'UPDATE_APPLIER_LIST_SUCCESS';
export const UPDATE_APPLIER_LIST_FAILURE = 'UPDATE_APPLIER_LIST_FAILURE';

//创建评价
export const CREATE_EVALUATE_REQUEST = 'CREATE_EVALUATE_REQUEST';
export const CREATE_EVALUATE_SUCCESS = 'CREATE_EVALUATE_SUCCESS';
export const CREATE_EVALUATE_FAILURE = 'CREATE_EVALUATE_FAILURE';
//获取评价
export const GET_EVALUATE_REQUEST = 'GET_EVALUATE_REQUEST';
export const GET_EVALUATE_SUCCESS = 'GET_EVALUATE_SUCCESS';
export const GET_EVALUATE_FAILURE = 'GET_EVALUATE_FAILURE';

//直接删除
export const DELETE_PROJECT_REQUEST = 'DELETE_PROJECT_REQUEST';
export const DELETE_PROJECT_SUCCESS = 'DELETE_PROJECT_SUCCESS';
export const DELETE_PROJECT_FAILURE = 'DELETE_PROJECT_FAILURE';
